// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menu-all'
  | 'menu-dual'
  | 'menu-mono'
  | 'menu-one-click'
  | 'menu-open-config'
  | 'menu-side-by-side'
  | 'menu-silent'
  | 'menu-translate-label'
  | 'pref-autofocus'
  | 'pref-autofocus-hint'
  | 'pref-browse'
  | 'pref-detect'
  | 'pref-exe-missing'
  | 'pref-exe-notfound'
  | 'pref-exe-ok'
  | 'pref-exepath'
  | 'pref-format'
  | 'pref-format-all'
  | 'pref-format-dual'
  | 'pref-format-hint'
  | 'pref-format-mono'
  | 'pref-format-side-by-side'
  | 'pref-link-hint'
  | 'pref-silent'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-finish';
