// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "format": string;
      "silent": boolean;
      "autoFocus": boolean;
      "exePath": string;
    };
  }
}
